/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_horizonremote_RemoteController */

#ifndef _Included_org_horizonremote_RemoteController
#define _Included_org_horizonremote_RemoteController
#ifdef __cplusplus
extern "C" {
#endif
#undef org_horizonremote_RemoteController_NULL_POINTER
#define org_horizonremote_RemoteController_NULL_POINTER 0LL
#undef org_horizonremote_RemoteController_STATE_FAILURE
#define org_horizonremote_RemoteController_STATE_FAILURE -2L
#undef org_horizonremote_RemoteController_STATE_DISCONNECTED
#define org_horizonremote_RemoteController_STATE_DISCONNECTED -1L
#undef org_horizonremote_RemoteController_STATE_CONNECTING
#define org_horizonremote_RemoteController_STATE_CONNECTING 0L
#undef org_horizonremote_RemoteController_STATE_CONNECTED
#define org_horizonremote_RemoteController_STATE_CONNECTED 1L
#undef org_horizonremote_RemoteController_KEY_POWER
#define org_horizonremote_RemoteController_KEY_POWER 57344L
#undef org_horizonremote_RemoteController_KEY_OK
#define org_horizonremote_RemoteController_KEY_OK 57345L
#undef org_horizonremote_RemoteController_KEY_BACK
#define org_horizonremote_RemoteController_KEY_BACK 57346L
#undef org_horizonremote_RemoteController_KEY_CHAN_UP
#define org_horizonremote_RemoteController_KEY_CHAN_UP 57350L
#undef org_horizonremote_RemoteController_KEY_CHAN_DWN
#define org_horizonremote_RemoteController_KEY_CHAN_DWN 57351L
#undef org_horizonremote_RemoteController_KEY_HELP
#define org_horizonremote_RemoteController_KEY_HELP 57353L
#undef org_horizonremote_RemoteController_KEY_MENU
#define org_horizonremote_RemoteController_KEY_MENU 57354L
#undef org_horizonremote_RemoteController_KEY_GUIDE
#define org_horizonremote_RemoteController_KEY_GUIDE 57355L
#undef org_horizonremote_RemoteController_KEY_INFO
#define org_horizonremote_RemoteController_KEY_INFO 57358L
#undef org_horizonremote_RemoteController_KEY_MENU1
#define org_horizonremote_RemoteController_KEY_MENU1 57361L
#undef org_horizonremote_RemoteController_KEY_MENU2
#define org_horizonremote_RemoteController_KEY_MENU2 57365L
#undef org_horizonremote_RemoteController_KEY_DPAD_UP
#define org_horizonremote_RemoteController_KEY_DPAD_UP 57600L
#undef org_horizonremote_RemoteController_KEY_DPAD_DOWN
#define org_horizonremote_RemoteController_KEY_DPAD_DOWN 57601L
#undef org_horizonremote_RemoteController_KEY_DPAD_LEFT
#define org_horizonremote_RemoteController_KEY_DPAD_LEFT 57602L
#undef org_horizonremote_RemoteController_KEY_DPAD_RIGHT
#define org_horizonremote_RemoteController_KEY_DPAD_RIGHT 57603L
#undef org_horizonremote_RemoteController_KEY_NUM_0
#define org_horizonremote_RemoteController_KEY_NUM_0 58112L
#undef org_horizonremote_RemoteController_KEY_NUM_1
#define org_horizonremote_RemoteController_KEY_NUM_1 58113L
#undef org_horizonremote_RemoteController_KEY_NUM_2
#define org_horizonremote_RemoteController_KEY_NUM_2 58114L
#undef org_horizonremote_RemoteController_KEY_NUM_3
#define org_horizonremote_RemoteController_KEY_NUM_3 58115L
#undef org_horizonremote_RemoteController_KEY_NUM_4
#define org_horizonremote_RemoteController_KEY_NUM_4 58116L
#undef org_horizonremote_RemoteController_KEY_NUM_5
#define org_horizonremote_RemoteController_KEY_NUM_5 58117L
#undef org_horizonremote_RemoteController_KEY_NUM_6
#define org_horizonremote_RemoteController_KEY_NUM_6 58118L
#undef org_horizonremote_RemoteController_KEY_NUM_7
#define org_horizonremote_RemoteController_KEY_NUM_7 58119L
#undef org_horizonremote_RemoteController_KEY_NUM_8
#define org_horizonremote_RemoteController_KEY_NUM_8 58120L
#undef org_horizonremote_RemoteController_KEY_NUM_9
#define org_horizonremote_RemoteController_KEY_NUM_9 58121L
#undef org_horizonremote_RemoteController_KEY_PAUSE
#define org_horizonremote_RemoteController_KEY_PAUSE 58368L
#undef org_horizonremote_RemoteController_KEY_STOP
#define org_horizonremote_RemoteController_KEY_STOP 58370L
#undef org_horizonremote_RemoteController_KEY_RECORD
#define org_horizonremote_RemoteController_KEY_RECORD 58371L
#undef org_horizonremote_RemoteController_KEY_FWD
#define org_horizonremote_RemoteController_KEY_FWD 58373L
#undef org_horizonremote_RemoteController_KEY_RWD
#define org_horizonremote_RemoteController_KEY_RWD 58375L
#undef org_horizonremote_RemoteController_KEY_MENU3
#define org_horizonremote_RemoteController_KEY_MENU3 61184L
#undef org_horizonremote_RemoteController_KEY_UNKNOWN_0
#define org_horizonremote_RemoteController_KEY_UNKNOWN_0 61190L
#undef org_horizonremote_RemoteController_KEY_UNKNOWN_1
#define org_horizonremote_RemoteController_KEY_UNKNOWN_1 61205L
#undef org_horizonremote_RemoteController_KEY_UNKNOWN_2
#define org_horizonremote_RemoteController_KEY_UNKNOWN_2 61207L
#undef org_horizonremote_RemoteController_KEY_UNKNOWN_3
#define org_horizonremote_RemoteController_KEY_UNKNOWN_3 61209L
#undef org_horizonremote_RemoteController_KEY_ONDEMAND
#define org_horizonremote_RemoteController_KEY_ONDEMAND 61224L
#undef org_horizonremote_RemoteController_KEY_DVR
#define org_horizonremote_RemoteController_KEY_DVR 61225L
#undef org_horizonremote_RemoteController_KEY_TV
#define org_horizonremote_RemoteController_KEY_TV 61226L
/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_horizonremote_RemoteController_nativeCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativeConnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_horizonremote_RemoteController_nativeConnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativeDisconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_horizonremote_RemoteController_nativeDisconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativeState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_horizonremote_RemoteController_nativeState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativeSendKey
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_org_horizonremote_RemoteController_nativeSendKey
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativeToggleKey
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_horizonremote_RemoteController_nativeToggleKey
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_horizonremote_RemoteController
 * Method:    nativePoll
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_horizonremote_RemoteController_nativePoll
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
