/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_horizonremote_jni_JNIReference */

#ifndef _Included_org_horizonremote_jni_JNIReference
#define _Included_org_horizonremote_jni_JNIReference
#ifdef __cplusplus
extern "C" {
#endif
#undef org_horizonremote_jni_JNIReference_NULL_POINTER
#define org_horizonremote_jni_JNIReference_NULL_POINTER 0LL
/*
 * Class:     org_horizonremote_jni_JNIReference
 * Method:    nativeDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_horizonremote_jni_JNIReference_nativeDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_horizonremote_jni_JNIReference
 * Method:    nativeCloneReference
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_horizonremote_jni_JNIReference_nativeCloneReference
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
